name: Container
on:
  push:
    branches:
    - main
    - release-*
  pull_request:
    branches:
    - main
    - release-*

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.ref }}
  cancel-in-progress: true

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  GORELEASER_VERSION: v1.10.3

jobs:
  build-binary:
    name: Build binary using goreleaser
    #needs: skip-check
    runs-on: ubuntu-latest
    timeout-minutes: 45
    #if: ${{ needs.skip-check.outputs.should_skip != 'true' }}
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version-file: go.mod
          check-latest: true
          cache: true

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: .node-version

      - name: Build binaries
        uses: goreleaser/goreleaser-action@v3
        with:
          distribution: goreleaser
          version: ${{ env.GORELEASER_VERSION }}
          args: build --rm-dist --skip-validate --snapshot --debug

      - name: Archive generated artifacts
        uses: actions/upload-artifact@v3
        with:
          name: pyrra-dist-binaries
          if-no-files-found: error
          path: |
            dist
            !dist/*.txt
  build-and-push-container:
    name: Container build and push
    needs: build-binary
    runs-on: ubuntu-latest
    timeout-minutes: 30
    permissions:
      #id-token: write
      packages: write
      contents: read
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: amd64.arm64,arm

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - uses: actions/download-artifact@v3
        with:
          name: pyrra-dist-binaries
          path: dist

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64, linux/arm64, linux/arm/v7
